#!/bin/bash

## PARACONFIG ##

# Configure locales
cat > /etc/locale.gen <<EOF
## PARACONFIG: do not remove this line ##

es_ES.UTF-8 UTF-8
en_US.UTF-8 UTF-8
EOF
locale-gen --purge en_US.UTF-8 es_ES.UTF-8
echo -e 'LANG="es_ES.UTF-8"\nLANGUAGE="es_ES:es"\n' > /etc/default/locale

# Configure UTC time zone
echo "Etc/UTC" > /etc/timezone
dpkg-reconfigure -f noninteractive tzdata

# Configure history
if ! grep -q "## PARACONFIG: do not remove this line ##" "/etc/profile"
then

cat >> /etc/profile <<EOF

## PARACONFIG: do not remove this line ##

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000
HISTFILESIZE=100000
HISTTIMEFORMAT='%F %T '
EOF
fi

# Upgrade system
apt-get update
apt-get dist-upgrade -y

# Install utilities
apt-get install bash-completion bmon ccze ethtool fail2ban glances htop iotop mtr psmisc rsync strace telnet vim -y
